#!/usr/bin/env python
"""Scaffold a new MushiBot agent.

Generates the agent class file (and, for trainable templates, a training
script stub), then appends a matching registry entry to
Agents/registry.py — the same three files guide.html walks through by
hand, just generated instead of copy-pasted.

Usage:
    python scripts/new_agent.py my_agent --template minimax
    python scripts/new_agent.py my_agent --template cnn

Templates:
    minimax  Non-trainable classical-search reference. Lands in
             Agents/classical/, kind="class", no training_script —
             modeled on basic_minimax.py.
    cnn      Trainable reference. Lands in Agents/rl/, kind="class",
             plus a Agents/training/<key>_training.py stub.

After running:
    1. Open the generated file(s) and replace the TODOs with real logic.
    2. Fill in the "description"/"architecture" TODOs in the appended
       registry entry.
    3. Verify the registry entry resolves: python -m Agents.registry
    4. Smoke-test it: python backend/simulator.py --mode local --p1 <key> --p2 random --n 1
"""

import argparse
import os
import re
import sys

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
REGISTRY_PATH = os.path.join(REPO_ROOT, "Agents", "registry.py")


def _pascal_case(key):
    return ''.join(part.capitalize() for part in re.split(r'[_\-]+', key) if part)


MINIMAX_BODY = '''"""{class_name} — generated by scripts/new_agent.py (minimax template).

Non-trainable classical-search reference. Replace choose_action() (and add
a real evaluate()) with your own decision rule; see
Agents/classical/basic_minimax.py for a complete worked example.

game.get_legal_actions() can include ('skip_bonus',) on a bonus turn and
6-element ('plant', 'Boat', r, c, dr, dc) actions; use Agents/actions.py's
action_kind()/plant_parts()/arrange_parts() instead of unpacking an action
tuple by a fixed length.
"""

import random


class {class_name}:
    def __init__(self, player=1, time_budget=1.0):
        self.player = player
        self.time_budget = float(time_budget)

    def choose_action(self, game, verbose=False):
        legal = game.get_legal_actions()
        if not legal:
            return None
        # TODO: replace with real search / evaluation.
        return random.choice(legal)
'''

CNN_BODY = '''"""{class_name} — generated by scripts/new_agent.py (cnn template).

Trainable reference. Replace the model with your own architecture and
save_model/load_model with your own persistence format; see
Agents/rl/cnn_basic.py for a complete worked example.

game.get_legal_actions() can include ('skip_bonus',) on a bonus turn and
6-element ('plant', 'Boat', r, c, dr, dc) actions; use Agents/actions.py's
action_kind()/plant_parts()/arrange_parts() instead of unpacking an action
tuple by a fixed length.
"""

import os
import random

from Agents.utils import DATA_DIR

MODEL_PATH = os.path.join(DATA_DIR, 'params', '{pascal}', '{key}.pt')


class {class_name}:
    def __init__(self, player=1, load=False, device='cpu'):
        self.player = player
        self.device = device
        # TODO: build your model here.
        if load:
            self.load_model()

    def choose_action(self, game, verbose=False):
        legal = game.get_legal_actions()
        if not legal:
            return None
        # TODO: replace with a real policy/value lookup.
        return random.choice(legal)

    def save_model(self, path=None):
        path = path or MODEL_PATH
        os.makedirs(os.path.dirname(path), exist_ok=True)
        # TODO: persist your model's weights to `path`.

    def load_model(self, path=None):
        path = path or MODEL_PATH
        if not os.path.exists(path):
            return
        # TODO: restore your model's weights from `path`.
'''

TRAINING_BODY = '''"""Training script for {key} — generated by scripts/new_agent.py.

Fill in the self-play loop; keep the EVENT: logging so the Train page's
progress bar and stats work. See Agents/training/cnn_basic_training.py
for a complete worked example (opponent loading, checkpointing, epsilon
decay, EVENT emission).
"""

import argparse

from PythonEngine.PaiShoGame import PaiShoGame
from Agents.rl.{key} import {class_name}
from Agents.training.opponent_utils import load_opponent
from Agents.logging_utils import get_logger, log_event

log = get_logger("{key}_training")


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--n', type=int, default=1000)
    p.add_argument('--lr', type=float, default=1e-3)
    p.add_argument('--eps', type=float, default=0.3)
    p.add_argument('--opponent', type=str, default='self')
    p.add_argument('--resume', action='store_true')
    args = p.parse_args()

    agent = {class_name}(player=1, load=args.resume)
    opponent = load_opponent(args.opponent)  # None means self-play

    for episode in range(1, args.n + 1):
        game = PaiShoGame()
        # TODO: play one episode (self-play if `opponent` is None, else let
        # `opponent(game)` choose player 2's moves), update the model from
        # the outcome.
        outcome, steps = "?", 0
        log_event(log, "episode", episode=episode, total=args.n,
                   outcome=outcome, steps=steps)
        if episode % 500 == 0:
            agent.save_model()
    agent.save_model()


if __name__ == "__main__":
    main()
'''

TEMPLATES = {
    "minimax": {"dir": "Agents/classical", "module_pkg": "Agents.classical", "body": MINIMAX_BODY, "trainable": False},
    "cnn":     {"dir": "Agents/rl",        "module_pkg": "Agents.rl",        "body": CNN_BODY,     "trainable": True},
}


def _trainable_entry(key, class_name, module, pascal):
    return f'''    {{
        "key": "{key}",
        "display_name": "{class_name}",
        "description": "TODO: one-line description shown on the model card",
        "architecture": "TODO: describe how this agent decides its moves.",
        "kind": "class",
        "module": "{module}",
        "class_name": "{class_name}",
        "play_kwargs": {{"player": 1, "load": True}},
        "needs_player": True,
        "play_params": [],
        "model_path": "data/params/{pascal}/{key}.pt",
        "training_script": "Agents/training/{key}_training.py",
        "training_params": [
            num_param("episodes", "Episodes", 1000, step=100, min=1, tooltip="Number of self-play episodes", cli_flag="--n"),
            num_param("lr", "Learning Rate", 0.001, step=0.0001, min=0.00001, max=1, tooltip="Optimizer learning rate", cli_flag="--lr"),
            num_param("epsilon", "Start Epsilon", 0.3, step=0.01, min=0, max=1, tooltip="Initial exploration rate", cli_flag="--eps"),
            text_param("opponent", "Opponent", "self", tooltip="Training opponent (filled in after registry is built)", cli_flag="--opponent"),
            checkbox_param("resume", "Resume from checkpoint", False, tooltip="Load existing weights and continue training", cli_flag="--resume"),
        ],
        "total_episodes_key": "episodes",
        "log_parser": None,
        "config_file": None,
    }},
'''


def _nontrainable_entry(key, class_name, module):
    return f'''    {{
        "key": "{key}",
        "display_name": "{class_name}",
        "description": "TODO: one-line description shown on the model card",
        "architecture": "TODO: describe how this agent decides its moves.",
        "kind": "class",
        "module": "{module}",
        "class_name": "{class_name}",
        "play_kwargs": {{"player": 1}},
        "needs_player": True,
        "play_params": [
            num_param("time_budget", "Time budget (s)", 1.0, step=0.1, min=0.1, max=30, tooltip="Per-move search time budget."),
        ],
        "model_path": None,
        "training_script": None,
        "training_params": [],
        "total_episodes_key": None,
        "log_parser": None,
        "config_file": None,
    }},
'''


def _insert_registry_entry(snippet):
    with open(REGISTRY_PATH, "r", encoding="utf-8") as f:
        text = f.read()

    marker = "\ndef _fill_opponent_tooltip"
    marker_idx = text.index(marker)
    close_idx = text.rindex("\n]\n", 0, marker_idx)  # end of the AGENTS list literal
    insert_at = close_idx + 1

    with open(REGISTRY_PATH, "w", encoding="utf-8") as f:
        f.write(text[:insert_at] + snippet + text[insert_at:])


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("key", help="registry key / module name, snake_case, e.g. my_agent")
    p.add_argument("--template", choices=sorted(TEMPLATES), default="cnn",
                    help="minimax = non-trainable search reference; cnn = trainable reference (default)")
    args = p.parse_args()

    key = args.key.strip().lower()
    if not re.fullmatch(r"[a-z][a-z0-9_]*", key):
        sys.exit(f"error: key must be snake_case (letters, digits, underscores, starting with a letter): {key!r}")

    with open(REGISTRY_PATH, "r", encoding="utf-8") as f:
        registry_text = f.read()
    if f'"key": "{key}"' in registry_text:
        sys.exit(f"error: '{key}' is already a registry key in {os.path.relpath(REGISTRY_PATH, REPO_ROOT)}")

    tmpl = TEMPLATES[args.template]
    class_name = _pascal_case(key) + "Agent"
    pascal = _pascal_case(key)
    module = f"{tmpl['module_pkg']}.{key}"

    agent_path = os.path.join(REPO_ROOT, tmpl["dir"], f"{key}.py")
    if os.path.exists(agent_path):
        sys.exit(f"error: {os.path.relpath(agent_path, REPO_ROOT)} already exists")

    os.makedirs(os.path.dirname(agent_path), exist_ok=True)
    with open(agent_path, "w", encoding="utf-8") as f:
        f.write(tmpl["body"].format(class_name=class_name, key=key, pascal=pascal))
    print(f"created {os.path.relpath(agent_path, REPO_ROOT)}")

    created = [agent_path]
    if tmpl["trainable"]:
        training_path = os.path.join(REPO_ROOT, "Agents", "training", f"{key}_training.py")
        if os.path.exists(training_path):
            sys.exit(f"error: {os.path.relpath(training_path, REPO_ROOT)} already exists")
        with open(training_path, "w", encoding="utf-8") as f:
            f.write(TRAINING_BODY.format(class_name=class_name, key=key))
        print(f"created {os.path.relpath(training_path, REPO_ROOT)}")
        created.append(training_path)
        snippet = _trainable_entry(key, class_name, module, pascal)
    else:
        snippet = _nontrainable_entry(key, class_name, module)

    _insert_registry_entry(snippet)
    print(f"appended a '{key}' entry to {os.path.relpath(REGISTRY_PATH, REPO_ROOT)}")

    print("\nNext steps:")
    print(f"  1. Fill in the TODOs in {', '.join(os.path.relpath(p, REPO_ROOT) for p in created)}")
    print(f"  2. Fill in the description/architecture TODOs for '{key}' in registry.py")
    print("  3. python -m Agents.registry                     # validates the new entry resolves")
    print(f"  4. python backend/simulator.py --mode local --p1 {key} --p2 random --n 1")


if __name__ == "__main__":
    main()
